-- =========================
-- KEYMAP HELP (:K)
-- =========================
vim.api.nvim_create_user_command("K", function()
  local lines = {
    "NEOVIM KEYMAP REFERENCE   (/ to search, q to quit)",
    "══════════════════════════════════════════════════════════════════",
    "",
    "── MOTION / NAVIGATION / MOVEMENT / CURSOR ──────────────────────",
    "  h j k l          left down up right | arrow move",
    "  w  b             next prev word | jump word forward backward",
    "  e  ge            end of word forward backward",
    "  0  ^  $          start first-char end of line | bol eol",
    "  gg G             top bottom of file | first last line",
    "  {  }             prev next paragraph | blank line jump",
    "  %                matching bracket paren brace | jump pair",
    "  f{c} F{c}        find char forward backward on line | inline search",
    "  t{c} T{c}        till char forward backward | before char",
    "  ;  ,             repeat f/t forward backward",
    "  Ctrl-d Ctrl-u    scroll down up half page | page movement",
    "  Ctrl-f Ctrl-b    scroll down up full page | page forward backward",
    "  zz zt zb         center top bottom cursor on screen | reposition",
    "  H M L            screen top middle bottom | visible cursor",
    "  ''{mark}         jump to mark | bookmark goto",
    "  Ctrl-o Ctrl-i    jump list back forward | prev next location",
    "",
    "── INSERT / TYPING / ENTER / EDIT MODE ──────────────────────────",
    "  i  I             insert before cursor / line start",
    "  a  A             append after cursor / line end",
    "  o  O             new line below above | open line",
    "  s  S             substitute char / line | replace and insert",
    "  c{motion}        change delete and enter insert | replace",
    "  cc  C            change line / to end of line",
    "  Ctrl-w           delete prev word in insert mode | backspace word",
    "  Ctrl-u           delete to line start in insert | clear line",
    "  Esc <Esc><Esc>   exit insert / terminal mode | normal mode",
    "",
    "── YANK / COPY / PASTE / PUT / REGISTER ─────────────────────────",
    "  yy  Y            yank copy line",
    "  y{motion}        yank copy text object | e.g. yw yank word",
    "  p  P             paste put after before cursor",
    "  \"{r}y           yank into register r | named register copy",
    "  \"{r}p           paste from register r | named register put",
    "  :reg             show registers | clipboard history list",
    "  Ctrl-r {r}       paste register in insert/cmd mode | insert reg",
    "",
    "── DELETE / REMOVE / CUT / ERASE ───────────────────────────────",
    "  d{motion} dd     delete remove no yank black hole | erase without copy",
    "  D                delete cut to end of line | remove rest",
    "  x  X             delete cut char forward backward | erase char",
    "  diw daw          delete inner around word | remove word",
    "  di\" da\"        delete inside around quotes | remove quoted",
    "  di( da(          delete inside around parens | remove block",
    "",
    "── YANK AND DELETE COMBINED / COPY AND REMOVE ───────────────────",
    "  <leader>d | <>dd  cut to clipboard | yank and delete copy and remove",
    "  \"_d              black hole delete | remove without yank copy",
    "",
    "── CHANGE / REPLACE / SUBSTITUTE / SWAP ────────────────────────",
    "  r{c}             replace single char | swap character",
    "  R                replace mode | overwrite type",
    "  cw ciw           change word | replace word",
    "  ci\" ca\"          change inside around quotes | replace string",
    "  ci( ca(          change inside around parens | replace block",
    "  :s/old/new/g     substitute replace in line | find and replace",
    "  :%s/old/new/g    substitute replace in file | global find replace",
    "  :%s/old/new/gc   substitute with confirm | interactive replace",
    "",
    "── UNDO / REDO / HISTORY ────────────────────────────────────────",
    "  u                undo last change | revert",
    "  Ctrl-r           redo | undo undo | forward history",
    "  U                undo all changes on line | restore line",
    "  :earlier {n}m    go back n minutes in undo history | time travel",
    "  :later {n}m      go forward n minutes in undo history",
    "",
    "── SEARCH / FIND / GREP / PATTERN ──────────────────────────────",
    "  /pattern         search forward | find text",
    "  ?pattern         search backward | find reverse",
    "  n  N             next prev search match | repeat find",
    "  *  #             search word under cursor forward backward",
    "  :noh             clear search highlight | remove highlight",
    "  <leader>fg       telescope live grep | search in files ripgrep",
    "  <leader>ff       telescope find files | fuzzy file search",
    "",
    "── VISUAL / SELECT / HIGHLIGHT ──────────────────────────────────",
    "  v                visual char mode | select characters",
    "  V                visual line mode | select lines",
    "  Ctrl-v           visual block mode | column select rectangle",
    "  gv               reselect last visual | repeat selection",
    "  o                move to other end of selection | swap corners",
    "  aw iw            text object word | select word",
    "  a\" i\"            text object quotes | select string",
    "  a( i(            text object parens | select block",
    "",
    "── INDENT / FORMAT / ALIGN ──────────────────────────────────────",
    "  >>  <<           indent dedent line | shift right left",
    "  >%  <%           indent dedent block | shift matching",
    "  =G               auto indent to end | format reindent",
    "  gg=G             auto indent whole file | reformat all",
    "  gq{motion}       wrap format text | reflow paragraph",
    "",
    "── BUFFER / FILE / TAB ──────────────────────────────────────────",
    "  <leader>r        recent files oldfiles | browse history",
    "  <leader>b        telescope buffers | list open files switch",
    "  <leader>ff       find files | open file picker",
    "  :w               write save file",
    "  :wa              write save all buffers",
    "  :q  :q!          quit / force quit | close exit",
    "  :wq  ZZ          save and quit | write exit",
    "  :e {file}        edit open file | load",
    "  :bn  :bp         next prev buffer | switch buffer",
    "  :bd              delete close buffer | remove buffer",
    "  :ls              list buffers | show open files",
    "",
    "── WINDOW / SPLIT / PANE ────────────────────────────────────────",
    "  Ctrl-w s         split horizontal | divide window",
    "  Ctrl-w v         split vertical | vsplit pane",
    "  Ctrl-w h/j/k/l   move between splits | navigate windows",
    "  Ctrl-w =         equalize window sizes | balance splits",
    "  Ctrl-w q         close window | remove split",
    "  Ctrl-w o         close all other windows | only keep current",
    "",
    "── LSP / CODE INTELLIGENCE / IDE ───────────────────────────────",
    "  gd               go to definition | jump to declaration",
    "  gr               go to references | find usages",
    "  K                hover documentation | show docs info",
    "  rn               rename symbol | refactor name change",
    "  [d  ]d           prev next diagnostic | error warning jump",
    "  Ctrl-Space       trigger completion | autocomplete show",
    "  Tab              accept completion | confirm suggest",
    "",
    "── MACRO / RECORD / REPEAT ──────────────────────────────────────",
    "  q{r}             record macro into register | start recording",
    "  q                stop recording macro",
    "  @{r}             play macro | run recording",
    "  @@               repeat last macro",
    "  .                repeat last change | redo action",
    "",
    "── TERMINAL / SHELL ─────────────────────────────────────────────",
    "  :term            open terminal | shell",
    "  <Esc><Esc>       exit terminal mode | back to normal",
    "",
    "── MISC ─────────────────────────────────────────────────────────",
    "  :K              this keymap reference | help shortcuts cheatsheet",
    "  ga               show char code ascii hex | char info",
    "  g~{m} gu{m} gU{m} toggle lower upper case | swap case",
    "  Ctrl-a Ctrl-x    increment decrement number | increase decrease",
    "  J                join lines | merge lines concatenate",
    "  ~                toggle case char | flip case",
    "",
  }

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].filetype = "help"
  vim.bo[buf].modifiable = false

  vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = math.floor(vim.o.columns * 0.85),
    height = math.floor(vim.o.lines * 0.85),
    row = math.floor(vim.o.lines * 0.07),
    col = math.floor(vim.o.columns * 0.07),
    style = "minimal",
    border = "rounded",
  })

  vim.keymap.set("n", "q", "<cmd>close<CR>", { buffer = buf, silent = true })
end, { desc = "Keymap help reference" })
